// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateTelegramBot(ctx context.Context, arg CreateTelegramBotParams) (TelegramBot, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	DeleteTelegramBot(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetTelegramBotByBotID(ctx context.Context, botID *int64) (TelegramBot, error)
	GetTelegramBotByID(ctx context.Context, id pgtype.UUID) (TelegramBot, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByTelegramID(ctx context.Context, telegramID *int64) (User, error)
	ListTelegramBots(ctx context.Context) ([]TelegramBot, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error)
	UpdateTelegramBot(ctx context.Context, arg UpdateTelegramBotParams) (TelegramBot, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UserExistsByTelegramID(ctx context.Context, telegramID *int64) (bool, error)
}

var _ Querier = (*Queries)(nil)
