// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telegram_bots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTelegramBot = `-- name: CreateTelegramBot :one
INSERT INTO
    telegram_bots (
        owner_id,
        bot_id,
        username,
        first_name,
        encrypted_token,
        encryption_version,
        "status",
        last_error,
        last_checked_at,
        revoked_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10
    ) RETURNING id,
    owner_id,
    bot_id,
    username,
    first_name,
    encrypted_token,
    encryption_version,
    "status",
    last_error,
    last_checked_at,
    revoked_at,
    created_at,
    updated_at
`

type CreateTelegramBotParams struct {
	OwnerID           pgtype.UUID      `json:"owner_id"`
	BotID             *int64           `json:"bot_id"`
	Username          string           `json:"username"`
	FirstName         *string          `json:"first_name"`
	EncryptedToken    []byte           `json:"encrypted_token"`
	EncryptionVersion int32            `json:"encryption_version"`
	Status            string           `json:"status"`
	LastError         *string          `json:"last_error"`
	LastCheckedAt     pgtype.Timestamp `json:"last_checked_at"`
	RevokedAt         pgtype.Timestamp `json:"revoked_at"`
}

func (q *Queries) CreateTelegramBot(ctx context.Context, arg CreateTelegramBotParams) (TelegramBot, error) {
	row := q.db.QueryRow(ctx, createTelegramBot,
		arg.OwnerID,
		arg.BotID,
		arg.Username,
		arg.FirstName,
		arg.EncryptedToken,
		arg.EncryptionVersion,
		arg.Status,
		arg.LastError,
		arg.LastCheckedAt,
		arg.RevokedAt,
	)
	var i TelegramBot
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BotID,
		&i.Username,
		&i.FirstName,
		&i.EncryptedToken,
		&i.EncryptionVersion,
		&i.Status,
		&i.LastError,
		&i.LastCheckedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTelegramBot = `-- name: DeleteTelegramBot :exec
DELETE FROM
    telegram_bots
WHERE
    id = $1
`

func (q *Queries) DeleteTelegramBot(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTelegramBot, id)
	return err
}

const getTelegramBotByBotID = `-- name: GetTelegramBotByBotID :one
SELECT
    id,
    owner_id,
    bot_id,
    username,
    first_name,
    encrypted_token,
    encryption_version,
    "status",
    last_error,
    last_checked_at,
    revoked_at,
    created_at,
    updated_at
FROM
    telegram_bots
WHERE
    bot_id = $1
`

func (q *Queries) GetTelegramBotByBotID(ctx context.Context, botID *int64) (TelegramBot, error) {
	row := q.db.QueryRow(ctx, getTelegramBotByBotID, botID)
	var i TelegramBot
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BotID,
		&i.Username,
		&i.FirstName,
		&i.EncryptedToken,
		&i.EncryptionVersion,
		&i.Status,
		&i.LastError,
		&i.LastCheckedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTelegramBotByID = `-- name: GetTelegramBotByID :one
SELECT
    id,
    owner_id,
    bot_id,
    username,
    first_name,
    encrypted_token,
    encryption_version,
    "status",
    last_error,
    last_checked_at,
    revoked_at,
    created_at,
    updated_at
FROM
    telegram_bots
WHERE
    id = $1
`

func (q *Queries) GetTelegramBotByID(ctx context.Context, id pgtype.UUID) (TelegramBot, error) {
	row := q.db.QueryRow(ctx, getTelegramBotByID, id)
	var i TelegramBot
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BotID,
		&i.Username,
		&i.FirstName,
		&i.EncryptedToken,
		&i.EncryptionVersion,
		&i.Status,
		&i.LastError,
		&i.LastCheckedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTelegramBots = `-- name: ListTelegramBots :many
SELECT
    id,
    owner_id,
    bot_id,
    username,
    first_name,
    encrypted_token,
    encryption_version,
    "status",
    last_error,
    last_checked_at,
    revoked_at,
    created_at,
    updated_at
FROM
    telegram_bots
ORDER BY
    created_at DESC
`

func (q *Queries) ListTelegramBots(ctx context.Context) ([]TelegramBot, error) {
	rows, err := q.db.Query(ctx, listTelegramBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelegramBot{}
	for rows.Next() {
		var i TelegramBot
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.BotID,
			&i.Username,
			&i.FirstName,
			&i.EncryptedToken,
			&i.EncryptionVersion,
			&i.Status,
			&i.LastError,
			&i.LastCheckedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTelegramBot = `-- name: UpdateTelegramBot :one
UPDATE
    telegram_bots
SET
    owner_id = $1,
    bot_id = $2,
    username = $3,
    first_name = $4,
    encrypted_token = $5,
    encryption_version = $6,
    "status" = $7,
    last_error = $8,
    last_checked_at = $9,
    revoked_at = $10,
    updated_at = NOW()
WHERE
    bot_id = $2 RETURNING id,
    owner_id,
    bot_id,
    username,
    first_name,
    encrypted_token,
    encryption_version,
    "status",
    last_error,
    last_checked_at,
    revoked_at,
    created_at,
    updated_at
`

type UpdateTelegramBotParams struct {
	OwnerID           pgtype.UUID      `json:"owner_id"`
	BotID             *int64           `json:"bot_id"`
	Username          string           `json:"username"`
	FirstName         *string          `json:"first_name"`
	EncryptedToken    []byte           `json:"encrypted_token"`
	EncryptionVersion int32            `json:"encryption_version"`
	Status            string           `json:"status"`
	LastError         *string          `json:"last_error"`
	LastCheckedAt     pgtype.Timestamp `json:"last_checked_at"`
	RevokedAt         pgtype.Timestamp `json:"revoked_at"`
}

func (q *Queries) UpdateTelegramBot(ctx context.Context, arg UpdateTelegramBotParams) (TelegramBot, error) {
	row := q.db.QueryRow(ctx, updateTelegramBot,
		arg.OwnerID,
		arg.BotID,
		arg.Username,
		arg.FirstName,
		arg.EncryptedToken,
		arg.EncryptionVersion,
		arg.Status,
		arg.LastError,
		arg.LastCheckedAt,
		arg.RevokedAt,
	)
	var i TelegramBot
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BotID,
		&i.Username,
		&i.FirstName,
		&i.EncryptedToken,
		&i.EncryptionVersion,
		&i.Status,
		&i.LastError,
		&i.LastCheckedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
